// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrwahpxrulpylpjmdbig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhyd2FocHhydWxweWxwam1kYmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDc1NjYsImV4cCI6MjA2MDU4MzU2Nn0.RzyELTgWdL1Cx-ufnVvfabRUOl4umt-wioH2vu8ejhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);